export { initDisk } from "./buz/disk.buzz";
export { updateDisk } from "./buz/disk.buzz";
export { writeDisk } from "./buz/disk.buzz";
export { readDisk } from "./buz/disk.buzz"
export { indexDisk  } from "./buz/disk.buzz";
export { load_listDisk  } from "./buz/disk.buzz";
export { copyDisk  } from "./buz/disk.buzz";
export { frameDisk  } from "./buz/disk.buzz";
export { batchDisk  } from "./buz/disk.buzz";
export { trashDisk  } from "./buz/disk.buzz";
export { ensureDisk  } from "./buz/disk.buzz";
export { deleteDisk  } from "./buz/disk.buzz";